<script setup>
import { ref, computed, onMounted } from 'vue'
import { supabase } from '@/utils/supabase'
// import { useNotificationStore } from '@/stores/useNotificationStore'
const pendingBalances = ref([])

const isPrinting = ref(false)

const printPendingBalances = () => {
  isPrinting.value = true

  // Calculate totals specifically for printing to ensure fresh values
  const printTotalPending = pendingBalances.value.reduce(
    (sum, item) => sum + (item.amountDue || 0),
    0,
  )
  const printOverdueCount = pendingBalances.value.filter((item) => item.daysOverdue > 0).length
  const printPendingCount = pendingBalances.value.length

  // Create a new window for printing
  const printWindow = window.open('', '_blank')

  // Generate the printable content
  const printContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Pending Balances Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #333; }
        .print-container { max-width: 1000px; margin: 0 auto; }
        .print-header { text-align: center; margin-bottom: 20px; }
        .print-header h1 { color: #1976D2; margin-bottom: 5px; }
        .print-header p { color: #666; margin-top: 0; }
        .stats-container { display: flex; justify-content: space-between; margin-bottom: 20px; }
        .stat-box { flex: 1; padding: 15px; margin: 0 5px; border-radius: 8px; background: #f5f5f5; }
        .stat-title { font-size: 14px; color: #666; margin-bottom: 5px; }
        .stat-value { font-size: 20px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #1976D2; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .status-pending { color: #FF9800; }
        .status-overdue { color: #F44336; }
        .print-footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        @page { size: auto; margin: 10mm; }
      </style>
    </head>
    <body>
      <div class="print-container">
        <div class="print-header">
          <h1>Pending Balances Report</h1>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div class="stats-container">
          <div class="stat-box">
            <div class="stat-title">Total Outstanding</div>
            <div class="stat-value">${formatCurrency(printTotalPending)}</div>
          </div>
          <div class="stat-box">
            <div class="stat-title">Overdue Payments</div>
            <div class="stat-value">${printOverdueCount}</div>
          </div>
          <div class="stat-box">
            <div class="stat-title">Pending Payments</div>
            <div class="stat-value">${printPendingCount}</div>
          </div>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Tenant Name</th>
              <th>Room #</th>
              <th>Amount Due</th>
              <th>Due Date</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            ${filteredBalances.value
              .map(
                (item) => `
              <tr>
                <td>${item.firstname || ''} ${item.lastname || ''}</td>
                <td>${item.room || 'Unassigned'}${item.bedSide ? ` (Bed ${item.bedSide})` : ''}</td>
                <td>${formatCurrency(item.amountDue)}</td>
                <td>
                  ${item.dueDate || '—'}
                  ${item.daysOverdue > 0 ? `<span style="color: #F44336;">(${item.daysOverdue}d)</span>` : ''}
                </td>
                <td class="status-${item.status}">
                  ${item.status === 'overdue' ? '⚠️ ' : ''}${item.status}
                </td>
              </tr>
            `,
              )
              .join('')}
          </tbody>
        </table>
        
        <div class="print-footer">
          <p>End of Report • Generated by Tenant Management System</p>
        </div>
      </div>
    </body>
    </html>
  `

  // Write the content to the new window
  printWindow.document.open()
  printWindow.document.write(printContent)
  printWindow.document.close()

  // Wait for content to load before printing
  printWindow.onload = () => {
    printWindow.focus()
    printWindow.print()
    printWindow.close()
    isPrinting.value = false
  }
}

// Fetch data from Supabase
const fetchPendingBalances = async () => {
  try {
    const { data, error } = await supabase
      .from('invoices')
      .select(
        `
        invoice_id,
        total_amount,
        due_date,
        status,
        outstanding_balance,
        users:users!invoice_id(
          user_id,
          firstname,
          lastname,
          contact_number,
          bed_assignments:bed_assignment!user_id(
            assignment_id,
            bed_side,
            date_assigned,
            rooms:rooms!room_id(
              room_id,
              room_number
            )
          )
        )
      `,
      )
      .eq('status', 'pending')

    if (error) throw error

    console.log('PendingBalances - Raw Data:', JSON.stringify(data, null, 2))

    pendingBalances.value = data.map((invoice) => {
      const user = invoice.users?.[0] || {}
      const assignment = user.bed_assignments?.[0] || {}
      const room = assignment.rooms || {}

      const daysOverdue = invoice.due_date
        ? Math.max(0, Math.floor((new Date() - new Date(invoice.due_date)) / (1000 * 60 * 60 * 24)))
        : 0

      console.log(
        'PendingBalances - Mapped user_id for',
        user.firstname,
        user.lastname,
        ':',
        user.user_id,
      )

      return {
        id: invoice.invoice_id,
        firstname: user.firstname,
        lastname: user.lastname,
        userId: user.user_id,
        room: room.room_number,
        bedSide: assignment.bed_side,
        dateAssigned: assignment.date_assigned
          ? new Date(assignment.date_assigned).toLocaleDateString()
          : null,
        contact: user.contact_number,
        amountDue: invoice.total_amount,
        outstandingBalance: invoice.outstanding_balance,
        dueDate: invoice.due_date
          ? new Date(invoice.due_date).toLocaleDateString('en-US', {
              month: 'short',
              day: '2-digit',
            })
          : null,
        status: daysOverdue > 0 ? 'overdue' : 'pending',
        daysOverdue: daysOverdue,
      }
    })

    console.log('PendingBalances - Processed Data:', JSON.stringify(pendingBalances.value, null, 2))
  } catch (err) {
    console.error('PendingBalances - Error fetching:', err)
  }
}

onMounted(() => {
  console.log('PendingBalances - Current origin:', window.location.origin)
  fetchPendingBalances()
})

// Computed totals
const totalPending = computed(() =>
  pendingBalances.value.reduce((sum, item) => sum + (item.amountDue || 0), 0),
)

const overdueCount = computed(
  () => pendingBalances.value.filter((item) => item.daysOverdue > 0).length,
)

const pendingCount = computed(() => pendingBalances.value.length)

// Formatting helpers
const formatCurrency = (value) => {
  if (!value) return '₱0.00'
  return new Intl.NumberFormat('en-PH', {
    style: 'currency',
    currency: 'PHP',
  }).format(value)
}

const getStatusColor = (status) => {
  switch (status) {
    case 'pending':
      return 'warning'
    case 'overdue':
      return 'error'
    case 'paid':
      return 'success'
    default:
      return 'grey'
  }
}

// Search and sorting
const searchQuery = ref('')
const sortBy = ref('dueDate')
const sortDesc = ref(false)

const filteredBalances = computed(() => {
  let result = [...pendingBalances.value]

  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase()
    result = result.filter(
      (item) =>
        (item.firstname + ' ' + item.lastname).toLowerCase().includes(query) ||
        (item.room?.toString() || '').includes(query),
    )
  }

  return result.sort((a, b) => {
    const aValue = a[sortBy.value]
    const bValue = b[sortBy.value]

    if (aValue == null) return sortDesc.value ? -1 : 1
    if (bValue == null) return sortDesc.value ? 1 : -1

    if (typeof aValue === 'string' && typeof bValue === 'string') {
      return sortDesc.value ? bValue.localeCompare(aValue) : aValue.localeCompare(bValue)
    }

    return sortDesc.value ? bValue - aValue : aValue - bValue
  })
})

const toggleSort = (column) => {
  sortDesc.value = sortBy.value === column ? !sortDesc.value : false
  sortBy.value = column
}

const getSortIcon = (column) => {
  if (sortBy.value !== column) return 'mdi-unfold-more-horizontal'
  return sortDesc.value ? 'mdi-sort-descending' : 'mdi-sort-ascending'
}

// ✅ Send Reminder Function (Triggers Notification)

const sendReminder = async () => {
  try {
    console.log('PendingBalances - Starting to send reminders')

    if (!pendingBalances.value.length) {
      const { error } = await supabase.from('notifications').insert({
        message: 'No tenants with pending balances to notify',
        type: 'info',
      })
      if (error) throw error
      console.log('PendingBalances - No pending tenants, notification saved to Supabase')
      return
    }

    console.log('PendingBalances - Sending reminders to', pendingBalances.value.length, 'tenants')

    const notifications = pendingBalances.value.map((tenant) => {
      const fullName = `${tenant.firstname} ${tenant.lastname}`.trim() || 'Unnamed Tenant'
      const message = `Reminder: ${fullName}, you have ₱${tenant.amountDue} due on ${tenant.dueDate || 'N/A'}${tenant.daysOverdue > 0 ? ` (${tenant.daysOverdue} days overdue)` : ''}`
      console.log('PendingBalances - Preparing reminder for tenantIdentifier:', tenant.userId)
      return {
        message,
        type: 'reminder',
        tenant_identifier: tenant.userId,
        status: tenant.status,
      }
    })

    notifications.unshift({
      message: `Sent reminders to ${pendingBalances.value.length} tenant(s) with pending balances`,
      type: 'success',
    })

    const { error } = await supabase.from('notifications').insert(notifications)
    if (error) throw error

    console.log('PendingBalances - Sent reminders, saved to Supabase')
  } catch (error) {
    console.error('PendingBalances - Error sending reminders:', error)
    await supabase.from('notifications').insert({
      message: `Failed to send reminders: ${error.message}`,
      type: 'error',
    })
  }
}
</script>

<template>
  <v-card class="pending-balance-card elevation-1" rounded="lg">
    <v-card-item>
      <template v-slot:prepend>
        <v-icon color="error" icon="mdi-clock-alert" size="large" class="mr-2"></v-icon>
      </template>
      <v-card-title class="text-h5 font-weight-bold">Pending Balances</v-card-title>
      <template v-slot:append>
        <v-btn
          variant="text"
          prepend-icon="mdi-printer"
          color="grey-darken-1"
          size="small"
          @click="printPendingBalances"
          :loading="isPrinting"
        >
          Print
        </v-btn>
      </template>
    </v-card-item>

    <v-divider class="mx-4"></v-divider>

    <v-card-text>
      <!-- Stats overview -->
      <div class="d-flex flex-wrap gap-4 my-4">
        <v-sheet
          rounded="xl"
          elevation="1"
          class="pa-4 flex-grow-1 bg-primary-lighten-5 d-flex align-center"
        >
          <v-avatar color="primary" class="mr-3">
            <v-icon color="white">mdi-currency-php</v-icon>
          </v-avatar>
          <div>
            <div class="text-caption text-medium-emphasis">Total Outstanding</div>
            <div class="text-h5 font-weight-bold">{{ formatCurrency(totalPending) }}</div>
          </div>
        </v-sheet>

        <v-sheet
          rounded="xl"
          elevation="1"
          class="pa-4 flex-grow-1 bg-error-lighten-5 d-flex align-center"
        >
          <v-avatar color="error" class="mr-3">
            <v-icon color="white">mdi-alert-circle</v-icon>
          </v-avatar>
          <div>
            <div class="text-caption text-medium-emphasis">Overdue Payments</div>
            <div class="text-h5 font-weight-bold">{{ overdueCount }}</div>
          </div>
        </v-sheet>

        <v-sheet
          rounded="xl"
          elevation="1"
          class="pa-4 flex-grow-1 bg-warning-lighten-5 d-flex align-center"
        >
          <v-avatar color="warning" class="mr-3">
            <v-icon color="white">mdi-timer-sand</v-icon>
          </v-avatar>
          <div>
            <div class="text-caption text-medium-emphasis">Pending Payments</div>
            <div class="text-h5 font-weight-bold">{{ pendingCount }}</div>
          </div>
        </v-sheet>
      </div>

      <!-- Search and actions -->
      <div class="d-flex align-center mb-4">
        <v-text-field
          v-model="searchQuery"
          placeholder="Search tenants or rooms..."
          prepend-inner-icon="mdi-magnify"
          density="compact"
          variant="outlined"
          hide-details
          single-line
        ></v-text-field>

        <v-spacer></v-spacer>

        <v-btn
          color="success"
          prepend-icon="mdi-send-check"
          variant="tonal"
          size="small"
          class="ml-2"
          @click="sendReminder"
        >
          Send Reminders
        </v-btn>
      </div>

      <!-- Table -->
      <v-table class="rounded-lg balance-table">
        <thead>
          <tr class="text-grey bg-grey-lighten-4">
            <th @click="toggleSort('firstname')" class="cursor-pointer">
              <div class="d-flex align-center">
                Tenant Name
                <v-icon size="small" class="ml-1">{{ getSortIcon('firstname') }}</v-icon>
              </div>
            </th>
            <th @click="toggleSort('room')" class="cursor-pointer">
              <div class="d-flex align-center">
                Room #
                <v-icon size="small" class="ml-1">{{ getSortIcon('room') }}</v-icon>
              </div>
            </th>
            <th @click="toggleSort('amountDue')" class="cursor-pointer">
              <div class="d-flex align-center">
                Amount Due
                <v-icon size="small" class="ml-1">{{ getSortIcon('amountDue') }}</v-icon>
              </div>
            </th>
            <th @click="toggleSort('dueDate')" class="cursor-pointer">
              <div class="d-flex align-center">
                Due Date
                <v-icon size="small" class="ml-1">{{ getSortIcon('dueDate') }}</v-icon>
              </div>
            </th>
            <th @click="toggleSort('status')" class="cursor-pointer">
              <div class="d-flex align-center">
                Status
                <v-icon size="small" class="ml-1">{{ getSortIcon('status') }}</v-icon>
              </div>
            </th>
          </tr>
        </thead>

        <tbody>
          <tr v-if="filteredBalances.length === 0">
            <td colspan="6" class="text-center py-4 text-grey">
              <v-icon size="large" class="mr-2">mdi-database-remove</v-icon>
              No pending balances found
            </td>
          </tr>

          <tr v-for="item in filteredBalances" :key="item.id" class="balance-row">
            <!-- Tenant Name -->
            <td class="font-weight-medium">
              <div class="d-flex align-center">
                <v-avatar size="32" color="grey-lighten-3" class="mr-2">
                  <span class="text-caption">
                    {{ (item.firstname?.[0] || '') + (item.lastname?.[0] || '') }}
                  </span>
                </v-avatar>
                <template v-if="item.firstname || item.lastname">
                  {{ item.firstname }} {{ item.lastname }}
                </template>
                <template v-else>
                  <span class="text-grey">No tenant</span>
                </template>
              </div>
            </td>

            <!-- Room Number -->
            <td>
              <template v-if="item.room">
                <v-chip size="small" color="black" variant="tonal">
                  {{ item.room }}
                  <template v-if="item.bedSide"> - Bed {{ item.bedSide }}</template>
                </v-chip>
              </template>
              <template v-else>
                <span class="text-grey">Unassigned</span>
              </template>
            </td>

            <!-- Amount Due -->
            <td class="font-weight-medium">{{ formatCurrency(item.amountDue) }}</td>

            <!-- Due Date -->
            <td>
              <div class="d-flex align-center">
                <v-icon
                  :color="item.daysOverdue > 0 ? 'error' : 'warning'"
                  size="small"
                  class="mr-1"
                >
                  {{ item.daysOverdue > 0 ? 'mdi-calendar-alert' : 'mdi-calendar-clock' }}
                </v-icon>
                {{ item.dueDate || '—' }}
                <span v-if="item.daysOverdue > 0" class="text-caption text-error ml-1"
                  >({{ item.daysOverdue }}d)</span
                >
              </div>
            </td>

            <!-- Status -->
            <td>
              <v-chip
                size="small"
                :color="getStatusColor(item.status)"
                variant="tonal"
                :prepend-icon="item.status === 'overdue' ? 'mdi-alert-circle' : 'mdi-clock-outline'"
              >
                {{ item.status }}
              </v-chip>
            </td>
          </tr>
        </tbody>
      </v-table>
    </v-card-text>
  </v-card>
</template>

<style scoped>
.pending-balance-card {
  border-radius: 16px;
  overflow: hidden;
  transition:
    transform 0.3s,
    box-shadow 0.3s;
}

.pending-balance-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 20px rgba(0, 0, 0, 0.12) !important;
}

.balance-table {
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: 8px;
}

.balance-row {
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
  transition: background-color 0.2s;
}

.balance-row:hover {
  background-color: rgba(0, 0, 0, 0.02);
}

.cursor-pointer {
  cursor: pointer;
}

.cursor-pointer:hover {
  background-color: rgba(0, 0, 0, 0.03);
}
</style>
